[2023-12-22T18:08:36.871+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liverpool_dag.send_email_on_failure manual__2023-12-22T18:06:29.265441+00:00 [queued]>
[2023-12-22T18:08:36.883+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liverpool_dag.send_email_on_failure manual__2023-12-22T18:06:29.265441+00:00 [queued]>
[2023-12-22T18:08:36.883+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-22T18:08:36.901+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): send_email_on_failure> on 2023-12-22 18:06:29.265441+00:00
[2023-12-22T18:08:36.906+0000] {standard_task_runner.py:57} INFO - Started process 271 to run task
[2023-12-22T18:08:36.909+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'liverpool_dag', 'send_email_on_failure', 'manual__2023-12-22T18:06:29.265441+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/liverpool.py', '--cfg-path', '/tmp/tmp6qd2_rxd']
[2023-12-22T18:08:36.912+0000] {standard_task_runner.py:85} INFO - Job 606: Subtask send_email_on_failure
[2023-12-22T18:08:36.978+0000] {task_command.py:416} INFO - Running <TaskInstance: liverpool_dag.send_email_on_failure manual__2023-12-22T18:06:29.265441+00:00 [running]> on host d017a9b7b4e6
[2023-12-22T18:08:37.084+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liverpool_dag' AIRFLOW_CTX_TASK_ID='send_email_on_failure' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T18:06:29.265441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T18:06:29.265441+00:00'
[2023-12-22T18:08:40.437+0000] {logging_mixin.py:154} INFO - Correo enviado con Ã©xito.
[2023-12-22T18:08:40.438+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-22T18:08:40.452+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=liverpool_dag, task_id=send_email_on_failure, execution_date=20231222T180629, start_date=20231222T180836, end_date=20231222T180840
[2023-12-22T18:08:40.500+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-22T18:08:40.525+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
