[2023-12-18T20:17:50.307+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-18T20:17:46.553480+00:00 [queued]>
[2023-12-18T20:17:50.330+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-18T20:17:46.553480+00:00 [queued]>
[2023-12-18T20:17:50.332+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-18T20:17:50.366+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): connect_to_db> on 2023-12-18 20:17:46.553480+00:00
[2023-12-18T20:17:50.380+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-12-18T20:17:50.384+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'liverpool_dag', 'connect_to_db', 'manual__2023-12-18T20:17:46.553480+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/liverpool.py', '--cfg-path', '/tmp/tmpjnizjudr']
[2023-12-18T20:17:50.404+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask connect_to_db
[2023-12-18T20:17:50.614+0000] {task_command.py:416} INFO - Running <TaskInstance: liverpool_dag.connect_to_db manual__2023-12-18T20:17:46.553480+00:00 [running]> on host d017a9b7b4e6
[2023-12-18T20:17:50.838+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liverpool_dag' AIRFLOW_CTX_TASK_ID='connect_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T20:17:46.553480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-18T20:17:46.553480+00:00'
[2023-12-18T20:17:50.894+0000] {utils.py:22} ERROR - Error al conectarse a la base de datos: Can't load plugin: sqlalchemy.dialects:***
[2023-12-18T20:17:50.895+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-18T20:17:50.911+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=liverpool_dag, task_id=connect_to_db, execution_date=20231218T201746, start_date=20231218T201750, end_date=20231218T201750
[2023-12-18T20:17:50.972+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-18T20:17:51.014+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
