[2023-12-21T14:28:51.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T14:28:11.047684+00:00 [queued]>
[2023-12-21T14:28:51.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T14:28:11.047684+00:00 [queued]>
[2023-12-21T14:28:51.193+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-21T14:28:51.486+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): connect_to_db> on 2023-12-21 14:28:11.047684+00:00
[2023-12-21T14:28:51.594+0000] {standard_task_runner.py:57} INFO - Started process 380 to run task
[2023-12-21T14:28:54.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'liverpool_dag', 'connect_to_db', 'manual__2023-12-21T14:28:11.047684+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/liverpool.py', '--cfg-path', '/tmp/tmpl2pl3q38']
[2023-12-21T14:28:55.999+0000] {standard_task_runner.py:85} INFO - Job 266: Subtask connect_to_db
[2023-12-21T14:29:01.782+0000] {task_command.py:416} INFO - Running <TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T14:28:11.047684+00:00 [running]> on host d017a9b7b4e6
[2023-12-21T14:29:03.064+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liverpool_dag' AIRFLOW_CTX_TASK_ID='connect_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T14:28:11.047684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T14:28:11.047684+00:00'
[2023-12-21T14:29:04.978+0000] {utils.py:22} ERROR - Error al conectarse a la base de datos: Can't load plugin: sqlalchemy.dialects:***
[2023-12-21T14:29:04.980+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-21T14:29:05.051+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=liverpool_dag, task_id=connect_to_db, execution_date=20231221T142811, start_date=20231221T142851, end_date=20231221T142905
[2023-12-21T14:29:05.320+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-21T14:29:05.496+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
