[2023-12-21T16:22:37.246+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T16:22:05.122993+00:00 [queued]>
[2023-12-21T16:22:37.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T16:22:05.122993+00:00 [queued]>
[2023-12-21T16:22:37.276+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-21T16:22:37.391+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): connect_to_db> on 2023-12-21 16:22:05.122993+00:00
[2023-12-21T16:22:37.568+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'liverpool_dag', 'connect_to_db', 'manual__2023-12-21T16:22:05.122993+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/liverpool.py', '--cfg-path', '/tmp/tmpgptwyy3s']
[2023-12-21T16:22:37.609+0000] {standard_task_runner.py:85} INFO - Job 310: Subtask connect_to_db
[2023-12-21T16:22:37.665+0000] {standard_task_runner.py:57} INFO - Started process 1159 to run task
[2023-12-21T16:22:37.960+0000] {task_command.py:416} INFO - Running <TaskInstance: liverpool_dag.connect_to_db manual__2023-12-21T16:22:05.122993+00:00 [running]> on host d017a9b7b4e6
[2023-12-21T16:22:38.336+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liverpool_dag' AIRFLOW_CTX_TASK_ID='connect_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T16:22:05.122993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T16:22:05.122993+00:00'
[2023-12-21T16:22:39.523+0000] {utils.py:23} ERROR - Error al conectarse a la base de datos: Can't load plugin: sqlalchemy.dialects:***
[2023-12-21T16:22:39.524+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-21T16:22:39.539+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=liverpool_dag, task_id=connect_to_db, execution_date=20231221T162205, start_date=20231221T162237, end_date=20231221T162239
[2023-12-21T16:22:39.707+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-21T16:22:39.771+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
